SELECT B.PRODUCT_ID, B.PRODUCT_NAME, (SUM(A.AMOUNT) * PRICE) AS TOTAL_SALES
FROM FOOD_ORDER AS A
JOIN FOOD_PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.PRODUCE_DATE LIKE '2022-05%'
GROUP BY A.PRODUCT_ID
ORDER BY (SUM(A.AMOUNT) * PRICE) DESC, B.PRODUCT_ID